name: Daily Commit

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  beat:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "wekers"
          git config --global user.email "fernando@wekers.org"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/wekers/DesafioTDDEventCity-.git

      - name: Create commit
        run: |
          echo "Daily update: $(date)" > abeat.txt
          git add abeat.txt
          git commit -m "docs: daily update $(date '+%Y-%m-%d')" || exit 0

      - name: Push changes
        run: git push origin HEAD:main
